### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by esticle** [ClaudeOps/ring-downloader#1]
Hi, 

Unsure if the code as it is today should be working so thought I'll give it a spin (after installing the requirements) - 

```
$ python3 ring-downloader.py
  File "ring-downloader.py", line 9
    CONFIG_FILE = f'{CONFIG_DIR}/config.ini'
```
I do not seem to have any luck with any variable set using f<something>

It must be something silly so appreciate any help!

**Comment by ClaudeOps** [comment]
are you having an issue the the f-strings? you need python 3.6 and newer to use them. or you could replace with something like:

`CONFIG_FILE = '{dirName}/config.ini'.format(dirName=CONFIG_DIR)`

which should work in python 3.1 and newer.

**Comment by esticle** [comment]
Thanks for this - oddly this was on Python3.5.3 but moved it to another machine on Python 3.6.9 and getting further without the f-strings issue.

However It is now stuck at:

```
$ python3 ring-downloader.py
Traceback (most recent call last):
  File "ring-downloader.py", line 47, in <module>
    myring = Ring(config['DEFAULT']['user_name'], config['DEFAULT']['password'])
TypeError: __init__() takes 2 positional arguments but 3 were given
```

This also happens with the supplied config.ini.
I can make it print config['DEFAULT']['user_name'] and config['DEFAULT']['password'] and it looks good, but the myring=Ring() call seems to think 3 were given?

Thanks!

**Comment by ClaudeOps** [comment]
pull down my latest code. I updated it last night to keep up with the ring_download 0.6.0 release

**Comment by esticle** [comment]
Thanks - last commit is still 4359563bd66ef8a9502538b824e436145f137f07 / Nov 23 2019 though.

**Comment by ClaudeOps** [comment]
oops. I'll push tonight.

**Comment by ClaudeOps** [comment]
try again. It works with two factor auth disabled.

**Comment by esticle** [comment]
Thanks - perfect now!
